# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('ddi_data', 'ddi_data'),
    ],
    hiddenimports=[
        'pymobiledevice3',
        'pymobiledevice3.lockdown',
        'pymobiledevice3.usbmux',
        'pymobiledevice3.services.amfi',
        'pymobiledevice3.services.mobile_image_mounter',
        'pymobiledevice3.services.heartbeat',
        'pymobiledevice3.services.lockdown_service',
        'pymobiledevice3.service_connection',
        'pymobiledevice3.pair_records',
        'pymobiledevice3.common',
        'pymobiledevice3.ca',
        'pymobiledevice3.irecv_devices',
        'pymobiledevice3.restore.tss',
        'pymobiledevice3.exceptions',
        'pymobiledevice3.lockdown_service_provider',
        'developer_disk_image',
        'developer_disk_image.repo',
        'packaging',
        'packaging.version',
        'zeroconf',
        'opack2',
        'construct',
        'asn1',
        'bpylist2',
        'cryptography',
        'srptools',
        'tqdm',
        'requests',
        'remotezip2',
        'ifaddr',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'uvicorn',
        'fastapi',
        'starlette',
        'matplotlib',
        'scipy',
        'pandas',
        'notebook',
        'jupyter',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='DevImageWin',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    icon=None,
)
